title: The Talk Groups
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site

mainLinks:
  - "THC"

forumLinks:
  - "General HR"
  - "Test Kits"
  - "Forum"

# Build settings
markdown: kramdown
