title: The Talk Groups
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site

exclude: [
    "node_modules", 
    "Gemfile", 
    "Gemfile.lock", 
    "package.json", 
    "typings.json", 
    "typings", 
    "ts"
]

defaults: 
    - values: 
        head: <script src="js/common.roll.js" async></script>

sass:
    style: compressed

markdown: kramdown

prose: 
    media: assets/content
    ignore: [
        "_includes", 
        "_layouts", 
        "_sass",
        "_data",
        "assets/static", 
        "assets/user-content",
        "package.json",
        "tsconfig.json",
        "typings.json",
        "Gemfile",
        "Gemfile.lock",
        ".gitignore",
        "_config.yml",
        "css",
        "js",
        "ts",
        "*.html",
        "*/forum/questions",
        "*/forum/tips-and-tricks",
        "*/forum/trip-reports"
    ]