title: The Talk Groups
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site

exclude: [node_modules, Gemfile, Gemfile.lock, package.json, typings.json, ts]

prose: 
    media: assets/content
    ignore: [
        "_includes", 
        "_layouts", 
        "assets/static", 
        "assets/user-content",
        "css",
        "js",
        "ts",
        "sign-in.html",
        "package.json",
        "tsconfig.json",
        "Gemfile",
        "Gemfile.lock",
        ".gitignore",
        "_config.yml"
    ]

# Build settings
markdown: kramdown
